Fixing broken System test
googleapis/google-cloud-python-happybase pull request #53
Opened 2018-11-14 21:03 UTC by sumit-ql

1. Added labels in instance.create() - system-tests
2. Added retry429 in instance.delete() - system-tests
3. updated Connection.create_table() to pass column families dict to low_level_table.
4. Updated unit tests

This also partially fix the issue https://github.com/googleapis/google-cloud-python-happybase/issues/45

2018-11-15 16:26 UTC, sumit-ql commented
@tseaver @sduskis Please review.

2018-11-15 18:14 UTC, sumit-ql commented
System tests still failing on python 3.x, working fine with python 2.x. I forgot to run system tests on py3.x.
So i will be fixing this.

2018-11-17 12:00 UTC, sumit-ql commented
@tseaver made changes to make system-tests running with py3.x. Most of the changes are related to str to bytes conversion.
Please review.

2018-11-26 18:43 UTC, sduskis commented
@googleapis/yoshi-python, can someone please review this?

2018-12-06 16:13 UTC, sumit-ql commented
@tseaver Can you please review this PR.

2018-12-10 17:24 UTC, sduskis commented
@googleapis/yoshi-python, can we please get a review?

2018-12-12 19:29 UTC, tseaver requested changes
As a user, I would be surprised / upset to pass row data with text keys into the library, and get the same data back, except with bytes keys.  If we are going to be returning row data with bytes keys, we need to document that fact somewhere.

2018-12-18 01:38 UTC, sduskis commented
@sumit-ql, it looks like there are some follow up comments

2018-12-18 20:53 UTC, sumit-ql commented on unit_tests/test_connection.py
> +        self.assertEqual(len(col_fam_dict), 3)
done.

2018-12-18 20:53 UTC, sumit-ql commented on system_tests/happybase.py
> +LABEL_KEY = u'python-system'
done.

2018-12-18 20:54 UTC, sumit-ql commented on src/google/cloud/happybase/table.py
> +        curr_cells = cells[column_family_id][column_qualifier.encode()]
done.

2018-12-18 20:57 UTC, sumit-ql commented on system_tests/happybase.py
> +            COL4.encode(): value4,
Removed all calls of .encode() from system tests, the clutter was because of the way python handles bytes strings differently in py2.x and py3.x

2018-12-18 22:26 UTC, merged